name: Publish NPM Package

on:
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3" # You can specify a specific Python version if needed

      - name: Run version update script
        run: |
          python update_versions.py

      - name: Commit and push changes (if applicable)
        run: |
          git config --global user.email "mattcroak718@gmail.com"
          git config --global user.name "macro6461"
          git add .
          git commit -m "New update for queuejs-bfs"
          git push origin main  # Or to your desired branch
