name: Update Versions, Tag Release, Publish NPM Package

on:
  workflow_dispatch:

permissions:
  contents: write # Ensure the bot has write permissions to the repository

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all commits and tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3" # You can specify a specific Python version if needed

      - name: Check if version is set
        run: |
          echo "VERSION=${{ env.VERSION }}"

      - name: Run Python script to publish to NPM
        id: publish_npm
        run: |
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Save the version as an environment variable
          echo "DEBUG: VERSION=$VERSION"  # Debugging line to check the version value
          echo "NPM_TOKEN=${{ secrets.NPM_TOKEN }}" >> $GITHUB_ENV
          python ./buildscripts/publish_to_npm.py # No need to pass $VERSION since the script fetches the version internally.
