name: Update Versions, Tag Release, Publish NPM Package

on:
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all commits and tags

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3" # You can specify a specific Python version if needed

      - name: Fetch repo and all tags
        run: |
          git fetch
          git fetch --tags
          git config --global user.email "mattcroak718@gmail.com"
          git config --global user.name "macro6461"

      - name: Run Python script to get version
        id: get_version
        run: |
          VERSION=$(python ./buildscripts/update_versions.py)
          echo "VERSION=$VERSION" >> $GITHUB_ENV  # Save the version as an environment variable

      - name: Run version update script
        run: |
          python ./buildscripts/update_versions.py  # No need to pass $VERSION since the script fetches the version internally

      - name: Tag and push changes
        run: |
          git tag v${{ env.VERSION }}  # Use the version saved in the environment
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/macro6461/queuejs-bfs.git v${{ env.VERSION }}
